### ISSUE TITLE
node  dbsync 报错

### ISSUE THREAD

**Issue by zhaixww** [ciey/NodeExpressAdmin#5]
在创建 数据库后  执行 node dbsync 报错 
Unhandled rejection SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client
不知道我哪里出错了 
楼主看到能否加我扣扣  821926186

**Comment by ciey** [comment]
检查mysql版本，如果是mysql版本>=8，可能会报此错误。请安装mysql5.6或5.7版本

http://ftp.ntu.edu.tw/MySQL/Downloads/MySQLInstaller/mysql-installer-community-5.7.28.0.msi
